# rubocop version: 1.10.0
# rubocop-performance version: 1.9.2
# rubocop-rails version: 2.9.1
# rubocop-rspec version: 2.2.0

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/node_modules/**/*'
    - '**/script/**/*'
    - '**/spec/test_app/**/*'
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - '**/db/schema.rb'
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1

Gemspec/DateAssignment:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true
Layout/CaseIndentation:
  IndentOneStep: true
Layout/ClassStructure:
  Enabled: true
Layout/EmptyLineAfterMultilineCondition:
  Enabled: true
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/LineLength:
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/db/migrate/**/*'
    - '**/spec/**/*'
  Max: 80
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Layout/SpaceBeforeFirstArg:
  Exclude:
    - '**/spec/factories/**/*'

Lint/AmbiguousAssignment:
  Enabled: true
# Disabled for specs to allow following pattern:
# expect { Foo.create }.to change { Foo.count }
Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/spec/**/*'
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyClass:
  Enabled: false
Lint/EmptyFile:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/HashCompareByIdentity:
  Enabled: true
Lint/IdentityComparison:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/MissingSuper:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NumberConversion:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RedundantSafeNavigation:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Lint/UselessTimes:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/**/*'
Metrics/BlockLength:
  Exclude:
    - '**/config/**/*'
    - '**/helpers/**/*'
    - '**/db/migrate/**/*'
    - '**/db/seeds/**/*'
    - '**/spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 5
Metrics/MethodLength:
  Max: 15
  Exclude:
    - '**/db/migrate/**/*'
Metrics/ModuleLength:
  Exclude:
    - '**/db/seeds/**/*'
Metrics/PerceivedComplexity:
  Max: 5

Naming/AccessorMethodName:
  Exclude:
    - '**/app/controllers/**/*'
Naming/BlockParameterName:
  AllowedNames:
    - id
    - x
    - y
    - k
    - v
    - _
Naming/MethodParameterName:
  AllowedNames:
    - id
    - x
    - y
    - _
Naming/VariableNumber:
  EnforcedStyle: snake_case

Performance/AncestorsInclude:
  Enabled: false
# We're preferring this from a stylistic point of view; it does not actually
# impact performance
Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/BlockGivenWithExplicitBlock:
  Enabled: true
# `foo.downcase == bar.downcase` is more readable than
# `foo.casecmp(bar).zero?`
Performance/Casecmp:
  Enabled: false
Performance/CaseWhenSplat:
  Enabled: true
Performance/CollectionLiteralInLoop:
  Enabled: true
Performance/ConstantRegexp:
  Enabled: true
Performance/IoReadlines:
  Enabled: true
Performance/MethodObjectAsBlock:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Performance/Sum:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/ArelStar:
  Enabled: true
Rails/AttributeDefaultBlockValue:
  Enabled: true
Rails/Blank:
  NilOrEmpty: false
  UnlessPresent: false
Rails/DefaultScope:
  Enabled: true
Rails/FilePath:
  EnforcedStyle: slashes
Rails/FindById:
  Enabled: true
# Keyword arguments aren't functionally equivalent to positional arguments.
# Using keyword arguments in controller specs makes the param keys strings and
# not symbols, even if adding `.with_indifferent_access`.
Rails/HttpPositionalArguments:
  Enabled: false
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
# There are often no reasonable defaults for not null columns
Rails/NotNullColumn:
  Enabled: false
Rails/Output:
  Exclude:
    - '**/db/seeds.rb'
    - '**/lib/tasks/**/*'
Rails/Pluck:
  Enabled: true
Rails/PluckId:
  Enabled: false
Rails/PluckInWhere:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ShortI18n:
  Enabled: false
Rails/SquishedSQLHeredocs:
  Enabled: false
Rails/UniqBeforePluck:
  EnforcedStyle: aggressive
Rails/WhereEquals:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereNot:
  Enabled: true

# Prefer eql
RSpec/BeEql:
  Enabled: false
RSpec/BeforeAfterAll:
  Exclude:
    - '**/spec/models/powers/*'
RSpec/ContextWording:
  Prefixes:
    - as
    - by
    - when
    - with
    - without
# No class to describe for feature tests
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
    - '**/spec/requests/**/*'
RSpec/EmptyLineAfterExample:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ImplicitSubject:
  Enabled: false
RSpec/InstanceVariable:
  Exclude:
    - '**/spec/models/powers/*'
RSpec/LeadingSubject:
  Enabled: false
RSpec/LetSetup:
  Exclude:
    - '**/spec/features/**/*'
    - '**/spec/requests/**/*'
RSpec/MessageChain:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/RepeatedIncludeExample:
  Enabled: true
RSpec/ReturnFromStub:
  Enabled: false
RSpec/StubbedMock:
  Enabled: true
RSpec/SubjectStub:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AccessorGrouping:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/AutoResourceCleanup:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: false
Style/ClassEqualityComparison:
  Enabled: true
Style/ClassMethodsDefinitions:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/DateTime:
  Enabled: true
Style/Documentation:
  Exclude:
    - '**/controllers/**/*'
    - '**/app/helpers/application_helper.rb'
    - '**/app/mailers/application_mailer.rb'
    - '**/app/models/application_record.rb'
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/EndlessMethod:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific
Style/FormatStringToken:
  Enabled: false
Style/GlobalStdStream:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashConversion:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/IpAddresses:
  Enabled: true
Style/Lambda:
  EnforcedStyle: literal
Style/KeywordParametersOrder:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/NumericPredicate:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: true
Style/OptionHash:
  Enabled: true
Style/RedundantArgument:
  Enabled: false
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Style/StaticClass:
  Enabled: false
Style/StringConcatenation:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/Send:
  Enabled: true
# Prevents self-documentation
Style/SingleLineBlockParams:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/StringMethods:
  Enabled: true

# Defaults; may make sense to change for specific projects
Layout/EmptyLineAfterGuardClause:
  Enabled: true

Rails/OrderById:
  Enabled: true
Rails/SaveBang:
  Enabled: true
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - '**/config/**/*'
    - '**/controllers/**/*'
    - '**/db/**/*'
    - '**/spec/**/*'
Style/RedundantBegin:
  Enabled: true
Style/ZeroLengthPredicate:
  Enabled: true
