# rubocop version: 1.10.0
# rubocop-performance version: 1.9.2
# rubocop-rails version: 2.9.1
# rubocop-rake version: 0.5.1
# rubocop-rspec version: 2.2.0
#
# In addition, feel free to use rubocop-md for linting Markdown files with Ruby
# code snippets

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/node_modules/**/*'
    - '**/script/**/*'
    - '**/spec/test_app/**/*'
    - '**/vendor/**/*'
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - '**/db/schema.rb'
  NewCops: enable
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1

Layout/CaseIndentation:
  IndentOneStep: true
Layout/ClassStructure:
  Enabled: true
Layout/EmptyLineAfterMultilineCondition:
  Enabled: true
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented
Layout/LineLength:
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/db/migrate/**/*'
    - '**/spec/**/*'
  Max: 80
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceBeforeFirstArg:
  Exclude:
    - '**/spec/factories/**/*'

# Disabled for specs to allow following pattern:
# expect { Foo.create }.to change { Foo.count }
Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/spec/**/*'
Lint/EmptyClass:
  Enabled: false
Lint/NumberConversion:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/**/*'
Metrics/BlockLength:
  Exclude:
    - '**/config/**/*'
    - '**/helpers/**/*'
    - '**/db/migrate/**/*'
    - '**/db/seeds/**/*'
    - '**/spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 5
Metrics/MethodLength:
  Max: 15
  Exclude:
    - '**/db/migrate/**/*'
Metrics/ModuleLength:
  Exclude:
    - '**/db/seeds/**/*'
Metrics/PerceivedComplexity:
  Max: 5

Naming/AccessorMethodName:
  Exclude:
    - '**/app/controllers/**/*'
Naming/BlockParameterName:
  AllowedNames:
    - id
    - x
    - y
    - k
    - v
    - _
Naming/MethodParameterName:
  AllowedNames:
    - id
    - x
    - y
    - _
Naming/VariableNumber:
  EnforcedStyle: snake_case

Performance/AncestorsInclude:
  Enabled: false
# We're preferring this from a stylistic point of view; it does not actually
# impact performance
Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true
# `foo.downcase == bar.downcase` is more readable than
# `foo.casecmp(bar).zero?`
Performance/Casecmp:
  Enabled: false
Performance/CaseWhenSplat:
  Enabled: true
Performance/IoReadlines:
  Enabled: true

Rails/Blank:
  NilOrEmpty: false
  UnlessPresent: false
Rails/DefaultScope:
  Enabled: true
Rails/FilePath:
  EnforcedStyle: slashes
# Keyword arguments aren't functionally equivalent to positional arguments.
# Using keyword arguments in controller specs makes the param keys strings and
# not symbols, even if adding `.with_indifferent_access`.
Rails/HttpPositionalArguments:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
# There are often no reasonable defaults for not null columns
Rails/NotNullColumn:
  Enabled: false
Rails/OrderById:
  Enabled: false
Rails/Output:
  Exclude:
    - '**/db/seeds.rb'
    - '**/lib/tasks/**/*'
Rails/ShortI18n:
  Enabled: false
Rails/SquishedSQLHeredocs:
  Enabled: false
Rails/UniqBeforePluck:
  EnforcedStyle: aggressive

# Prefer eq
RSpec/BeEql:
  Enabled: false
RSpec/BeforeAfterAll:
  Exclude:
    - '**/spec/models/powers/*'
RSpec/ContextWording:
  Prefixes:
    - as
    - by
    - when
    - with
    - without
# No class to describe for feature tests
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
    - '**/spec/requests/**/*'
RSpec/DescribedClassModuleWrapping:
  Enabled: true
RSpec/EmptyLineAfterExample:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ImplicitSubject:
  Enabled: false
RSpec/InstanceVariable:
  Exclude:
    - '**/spec/models/powers/*'
RSpec/LeadingSubject:
  Enabled: false
RSpec/LetSetup:
  Exclude:
    - '**/spec/features/**/*'
    - '**/spec/requests/**/*'
RSpec/MessageChain:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ReturnFromStub:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/ArrayCoercion:
  Enabled: true
Style/AutoResourceCleanup:
  Enabled: true
Style/ClassMethodsDefinitions:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/DateTime:
  Enabled: true
Style/Documentation:
  Exclude:
    - '**/app/helpers/application_helper.rb'
    - '**/app/mailers/application_mailer.rb'
    - '**/app/models/application_record.rb'
    - '**/controllers/**/*'
    - '**/db/migrate/**/*'
    - '**/presenters/**/*'
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/ExponentialNotation:
  EnforcedStyle: scientific
Style/FormatStringToken:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/IpAddresses:
  Enabled: true
Style/Lambda:
  EnforcedStyle: literal
Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - '**/config/**/*'
    - '**/db/migrate/**/*'
    - '**/spec/**/*'
  AllowedMethods:
    # ActiveModel/ActiveRecord
    - accepts_nested_attributes_for
    - alias_attribute
    - attr_readonly
    - enum
    - belongs_to
    - has_many
    - has_one
    - has_many_attached
    - has_one_attached
    - has_rich_text
    - delegate
    - validate
    - validates
    - validates_with
    - before_validation
    - after_validation
    - before_save
    - around_save
    - before_create
    - around_create
    - after_create
    - after_save
    - after_commit
    - after_rollback
    - before_update
    - around_update
    - after_update
    - before_destroy
    - around_destroy
    - after_destroy
    - scope
    # ActionController
    - after_action
    - around_action
    - before_action
    - redirect_to
    - render
    # CarrierWave
    - store
    - mount_uploader
    # Consul
    - power
Style/MultilineMethodSignature:
  Enabled: true
Style/NumericPredicate:
  Enabled: false
Style/OptionHash:
  Enabled: true
Style/RedundantArgument:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/Send:
  Enabled: true
Style/SlicingWithRange:
  Enabled: false
Style/StringMethods:
  Enabled: true
Style/TrailingCommaInBlockArgs:
  Enabled: true

# Defaults; may make sense to change for specific projects
Layout/EmptyLineAfterGuardClause:
  Enabled: true

Rails/SaveBang:
  Enabled: true
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - '**/config/**/*'
    - '**/controllers/**/*'
    - '**/db/**/*'
    - '**/spec/**/*'
Style/RedundantBegin:
  Enabled: true
Style/ZeroLengthPredicate:
  Enabled: true
