# rubocop version: 0.75.1
# rubocop-performance version: 1.5.0
# rubocop-rails version: 2.3.2
# rubocop-rspec version: 1.36.0

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/node_modules/**/*'
    - '**/script/**/*'
    - '**/spec/test_app/**/*'
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - '**/db/schema.rb'
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0

Layout/ClassStructure:
  Enabled: true
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceBeforeFirstArg:
  Exclude:
    - '**/spec/factories/**/*'

# Disabled for specs to allow following pattern:
# expect { Foo.create }.to change { Foo.count }
Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/spec/**/*'
Lint/NumberConversion:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/**/*'
Metrics/BlockLength:
  Exclude:
    - '**/config/**/*'
    - '**/helpers/**/*'
    - '**/db/migrate/**/*'
    - '**/db/seeds/**/*'
    - '**/spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 5
Metrics/LineLength:
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/db/migrate/**/*'
    - '**/spec/**/*'
  Max: 80
Metrics/MethodLength:
  Max: 15
  Exclude:
    - '**/db/migrate/**/*'
Metrics/ModuleLength:
  Exclude:
    - '**/db/seeds/**/*'
Metrics/PerceivedComplexity:
  Max: 5

Naming/AccessorMethodName:
  Exclude:
    - '**/app/controllers/**/*'
Naming/UncommunicativeBlockParamName:
  AllowedNames:
    - id
    - x
    - y
    - _
Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - id
    - x
    - y
    - _
Naming/VariableNumber:
  EnforcedStyle: snake_case

# `foo.downcase == bar.downcase` is more readable than
# `foo.casecmp(bar).zero?`
Performance/Casecmp:
  Enabled: false
Performance/CaseWhenSplat:
  Enabled: true

Rails/Blank:
  NilOrEmpty: false
  UnlessPresent: false
# Keyword arguments aren't functionally equivalent to positional arguments.
# Using keyword arguments in controller specs makes the param keys strings and
# not symbols, even if adding `.with_indifferent_access`.
Rails/HttpPositionalArguments:
  Enabled: false
# There are often no reasonable defaults for not null columns
Rails/NotNullColumn:
  Enabled: false
Rails/Output:
  Exclude:
    - '**/db/seeds.rb'
    - '**/lib/tasks/**/*'
Rails/UniqBeforePluck:
  EnforcedStyle: aggressive

# Prefer eql
RSpec/BeEql:
  Enabled: false
RSpec/BeforeAfterAll:
  Exclude:
    - '**/spec/models/powers/*'
RSpec/ContextWording:
  Prefixes:
    - by
    - when
    - with
    - without
# No class to describe for feature tests
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
RSpec/EmptyLineAfterExample:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ImplicitSubject:
  Enabled: false
RSpec/InstanceVariable:
  Exclude:
    - '**/spec/models/powers/*'
RSpec/LeadingSubject:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ReturnFromStub:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AutoResourceCleanup:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/DateTime:
  Enabled: true
Style/Documentation:
  Exclude:
    - '**/controllers/**/*'
    - '**/app/helpers/application_helper.rb'
    - '**/app/mailers/application_mailer.rb'
    - '**/app/models/application_record.rb'
Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - '**/config/**/*'
    - '**/controllers/**/*'
    - '**/db/**/*'
    - '**/spec/**/*'
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FormatStringToken:
  Enabled: false
Style/IpAddresses:
  Enabled: true
Style/Lambda:
  EnforcedStyle: literal
Style/NumericPredicate:
  Enabled: false
Style/OptionHash:
  Enabled: true
Style/Send:
  Enabled: true
# Prevents self-documentation
Style/SingleLineBlockParams:
  Enabled: false
Style/StringMethods:
  Enabled: true

# Defaults; may make sense to change for specific projects
Layout/EmptyLineAfterGuardClause:
  Enabled: true

Rails/SaveBang:
  Enabled: true

RSpec/LetSetup:
  Exclude:
    - '**/spec/features/**/*'

Style/RedundantBegin:
  Enabled: true
Style/SafeNavigation:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: true
