require: rubocop-rspec

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/components/**/spec/test_app/**/*'
    - '**/config/**/*'
    - '**/db/schema.rb'
    - '**/script/**/*'
    - '**/spec/rails_helper.rb'
    - '**/spec/spec_helper.rb'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - '**/*.gemspec'
  DisplayCopNames: true
  RunRailsCops: true
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/**/*'
Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
Metrics/LineLength:
  Exclude:
    - '**/spec/**/*'
  Max: 80
Metrics/MethodLength:
  Exclude:
    - '**/db/migrate/**/*'

Style/CollectionMethods:
  Enabled: true
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/spec/factories/**'

Rails/Output:
  Exclude:
    - '**/db/seeds.rb'
    - '**/lib/tasks/**/*'
