# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
require_relative 'config/application'

Rails.application.load_tasks
if Rails.env.test? || Rails.env.development?
  require 'rspec/core/rake_task'
  
  task :js_tests do
    sh 'yarn test'
  end
  
  task :rubocop do
    sh 'rubocop --fail-level convention'
  end
    
  task :rubycritic do
    sh 'rubycritic'
  end
  
  task :eslint do
    sh 'yarn run eslint'
  end
  
  task :bundler_audit do
    sh 'bundle audit'
  end
  
  task default: [:spec, :js_tests, :rubocop, :rubycritic, :eslint, :bundler_audit]
  task ci:      [:default]
end
